### ISSUE TITLE
Audio Generator fails because player not started before getting stream playback.

### ISSUE THREAD

**Issue by blackears** [godotengine/godot-demo-projects#913]
**Which demo project is affected:**

Audio Generator

**OS/device including version:**
Windows 10

**Issue description:**

https://github.com/godotengine/godot/issues/76324

Tried to use Audio Generator demo with Godot 4.  If failed with an error due to `$Player.get_stream_playback()` returning null.  However, moving the line `$Player.play()` to the line before this one resolved the issue.

**Screenshots of issue:**

**Comment by moth-boi** [comment]
I gave it a try and it looks like the issue has been fixed. Everything seems to be working. This issue can be closed.

**Comment by PreetomBoro** [comment]
@zf-moth hi, the zip file in https://godotengine.org/asset-library/asset/2759 still doesn't reflect the changes. Thanks.
